export const initialEmployees = [
  {
    id: 1,
    empid: "E001",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice@example.com",
    department: "HR",
    role: "Manager",
    status: "Active",
    dateofjoining: "2022-01-15",
  },
  {
    id: 2,
    empid: "E002",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob@example.com",
    department: "IT",
    role: "Developer",
    status: "Inactive",
    dateofjoining: "2023-03-10",
  },
  {
    id: 3,
    empid: "E003",
    firstName: "Charlie",
    lastName: "Lee",
    email: "charlie@example.com",
    department: "Finance",
    role: "Analyst",
    status: "Active",
    dateofjoining: "2024-05-20",
  },
];
